# Shell variables
# Generated by 'wal'
wallpaper='/home/dschlack/Bilder/Wallpaper/land1.jpg'

# Special
background='#1e0b0f'
foreground='#98a3a1'
cursor='#98a3a1'

# Colors
color0='#1e0b0f'
color1='#344854'
color2='#5E5656'
color3='#AB5842'
color4='#9F6858'
color5='#AF8672'
color6='#E49571'
color7='#98a3a1'
color8='#6a7270'
color9='#344854'
color10='#5E5656'
color11='#AB5842'
color12='#9F6858'
color13='#AF8672'
color14='#E49571'
color15='#98a3a1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
