# Shell variables
# Generated by 'wal'
wallpaper='/home/dschlack/Bilder/Wallpaper/pixel1.jpg'

# Special
background='#031013'
foreground='#89b4b1'
cursor='#89b4b1'

# Colors
color0='#031013'
color1='#1C5952'
color2='#5E6553'
color3='#6C6D55'
color4='#807B65'
color5='#6F846F'
color6='#8C8B72'
color7='#89b4b1'
color8='#5f7d7b'
color9='#1C5952'
color10='#5E6553'
color11='#6C6D55'
color12='#807B65'
color13='#6F846F'
color14='#8C8B72'
color15='#89b4b1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
