# Shell variables
# Generated by 'wal'
wallpaper='/home/dschlack/.config/wpg/wallpapers/soldark.jpg'

# Special
background='#002b36'
foreground='#657b83'
cursor='#838d90'

# Colors
color0='#002b36'
color1='#dc322f'
color2='#859900'
color3='#b58900'
color4='#268bd2'
color5='#6c71c4'
color6='#2aa198'
color7='#93a1a1'
color8='#657b83'
color9='#dc322f'
color10='#859900'
color11='#b58900'
color12='#268bd2'
color13='#6c71c4'
color14='#2aa198'
color15='#657b83'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
